export const COUNTRY_MAP = {
    "The United Arab Emirates": "United Arab Emirates",
    "Antigua And Barbuda": "Antigua and Barb.",
    "Bosnia And Herzegovina": "Bosnia and Herz.",
    "Brunei Darussalam": "Brunei",
    "The Bahamas": "Bahamas",
    "The Democratic Republic Of The Congo": "Dem. Rep. Congo",
    "The Central African Republic": "Central African Rep.",
    "The Congo": "Congo",
    "Coted Ivoire": "Côte d'Ivoire",
    "The Cook Islands": "Cook Is.",
    "Curacao": "Curaçao",
    "The Dominican Republic": "Dominican Rep.",
    "The Falkland Islands Malvinas": "Falkland Is.",
    "The Faroe Islands": "Faeroe Is.",
    "The United Kingdom Of Great Britain And Northern Ireland": "United Kingdom",
    "The Gambia": "Gambia",
    "Equatorial Guinea": "Eq. Guinea",
    "Guinea Bissau": "Guinea-Bissau",
    "Isle Of Man": "Isle of Man",
    "British Indian Ocean Territory": "Br. Indian Ocean Ter.",
    "Islamic Republic Of Iran": "Iran",
    "The Comoros": "Comoros",
    "Saint Kitts And Nevis": "St. Kitts and Nevis",
    "The Democratic Peoples Republic Of Korea": "North Korea",
    "The Republic Of Korea": "South Korea",
    "The Cayman Islands": "Cayman Is.",
    "The Lao Peoples Democratic Republic": "Laos",
    "The Republic Of Moldova": "Moldova",
    "The Marshall Islands": "Marshall Is.",
    "Republic Of North Macedonia": "Macedonia",
    "The Niger": "Niger",
    "The Netherlands": "Netherlands",
    "French Polynesia": "Fr. Polynesia",
    "The Philippines": "Philippines",
    "Saint Pierre And Miquelon": "St. Pierre and Miquelon",
    "State Of Palestine": "Palestine",
    "The Russian Federation": "Russia",
    "Solomon Islands": "Solomon Is.",
    "The Sudan": "Sudan",
    "South Sudan": "S. Sudan",
    "Sao Tome And Principe": "São Tomé and Principe",
    "Syrian Arab Republic": "Syria",
    "Eswatini": "eSwatini",
    "The Turks And Caicos Islands": "Turks and Caicos Is.",
    "Timor Leste": "Timor-Leste",
    "Türkiye": "Turkey",
    "Trinidad And Tobago": "Trinidad and Tobago",
    "Taiwan, Republic Of China": "Taiwan",
    "United Republic Of Tanzania": "Tanzania",
    "The United States Of America": "United States of America",
    "Saint Vincent And The Grenadines": "St. Vin. and Gren.",
    "Bolivarian Republic Of Venezuela": "Venezuela",
    "British Virgin Islands": "British Virgin Is.",
    "US Virgin Islands": "U.S. Virgin Is.",
    "Wallis And Futuna": "Wallis and Futuna Is."
};

export function normalizeCountry(name) {
    return COUNTRY_MAP[name] || name;
}
